In [6]:
def countItems(item, l):
    return len(list(filter(lambda x : x == item, l)))

In [7]:
a = [1, 2, 3, 4, 42, 10, 11, 42.0]
countItems(42, a)

2

In [8]:
def countFunctionCreator(item):
    def countFunction(x):
        return x == item
    return countFunction

In [9]:
countFunctionCreator(23)

<function __main__.countFunctionCreator.<locals>.countFunction>

In [10]:
len(list(filter(countFunctionCreator(42), a)))

2

In [11]:
len(list(filter(countFunctionCreator(23), a)))

0

In [12]:
[1, 3, 6, 10, 15, 21]

[1, 3, 6, 10, 15, 21]

In [13]:
[n * (n + 1) // 2 for n in range(1, 10)]

[1, 3, 6, 10, 15, 21, 28, 36, 45]

In [15]:
[sum(range(1, n + 1)) for n in range(1, 10)]

[1, 3, 6, 10, 15, 21, 28, 36, 45]

In [19]:
def sumGenerator():
    s = 0
    def sumFn(x):
        nonlocal s
        s = s + x
        return s
    return sumFn

In [20]:
f = sumGenerator()

In [21]:
f(8)

8

In [22]:
f(7)

15

In [23]:
g = sumGenerator()

In [24]:
g(8)

8

In [25]:
f(1)

16

In [26]:
g(2)

10

In [27]:
f = sumGenerator()
[f(i) for i in range(1, 10)]

[1, 3, 6, 10, 15, 21, 28, 36, 45]

In [28]:
sin(3.141)

NameError: name 'sin' is not defined

In [29]:
import math

In [30]:
sin(3.141)

NameError: name 'sin' is not defined

In [31]:
math.sin(3.141)

0.0005926535550994539

In [32]:
sinus = math.sin
sinus(0.1)

0.09983341664682815

In [33]:
from math import cos

In [34]:
cos(3.141529)

-0.9999999979741102

In [35]:
from math import tan as tangens

In [36]:
tangens(0)

0.0

In [37]:
import numpy as np

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
range(10)

range(0, 10)

In [40]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
range(10.0)

TypeError: 'float' object cannot be interpreted as an integer

In [42]:
np.arange(10.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [43]:
np.arange(1.0, 2.0, 0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9])

In [44]:
x = 0
for i in np.arange(1.0, 2.0, 0.1):
    x += i
x

14.500000000000004

In [46]:
np.arange(1.0, 2.0, 0.1).reshape(2, 5)

array([[ 1. ,  1.1,  1.2,  1.3,  1.4],
       [ 1.5,  1.6,  1.7,  1.8,  1.9]])

In [47]:
np.arange(10).dtype

dtype('int32')

In [48]:
np.arange(10.0).dtype

dtype('float64')

In [50]:
x = np.arange(1, 10)

In [51]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
3 * x

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [53]:
y = np.arange(3, 30, 3)

In [54]:
y

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [55]:
x + y

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [56]:
x * y

array([  3,  12,  27,  48,  75, 108, 147, 192, 243])

In [57]:
x = np.linspace(0, 2 * np.pi, 1000)
x[980:1000]

array([ 6.16368529,  6.16997476,  6.17626424,  6.18255371,  6.18884319,
        6.19513266,  6.20142214,  6.20771161,  6.21400108,  6.22029056,
        6.22658003,  6.23286951,  6.23915898,  6.24544846,  6.25173793,
        6.25802741,  6.26431688,  6.27060636,  6.27689583,  6.28318531])

In [58]:
math.sin(x)

TypeError: only length-1 arrays can be converted to Python scalars

In [59]:
y = np.sin(x)
y[990:1000]

array([ -5.65750492e-02,  -5.02945704e-02,  -4.40121020e-02,
        -3.77278927e-02,  -3.14421909e-02,  -2.51552454e-02,
        -1.88673048e-02,  -1.25786178e-02,  -6.28943332e-03,
        -2.44929360e-16])

In [60]:
x1 = [float(i) for i in range(1, 10000000)]
x2 = np.array(x1)

In [61]:
%timeit sum([k*k for k in x1])

1 loops, best of 3: 979 ms per loop


In [62]:
%timeit (x2 * x2).sum()

10 loops, best of 3: 45.8 ms per loop


In [63]:
a = np.arange(1, 20)

In [64]:
a % 3

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1], dtype=int32)

In [65]:
a % 3 != 0

array([ True,  True, False,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True, False,  True,  True, False,  True], dtype=bool)

In [66]:
a[a % 3 != 0]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19])

In [67]:
def eratosthenes(n):
    a = np.arange(2, n + 1)
    primes = []
    lim = math.sqrt(n)
    p = 2
    while p <= lim:
        a = a[a % p != 0]
        primes.append(p)
        p = a[0]
    primes.extend(a)
    return primes

In [68]:
eratosthenes(42)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41]

In [69]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(10).shape

(10,)

In [71]:
x = np.arange(10).reshape(1, 10)
x

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [72]:
x.shape

(1, 10)

In [74]:
y = np.arange(10).reshape(10, 1)
y

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [75]:
y.shape

(10, 1)

In [76]:
x.transpose()

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
x + y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])